all: outline talk

talk: *.tex
	pdflatex talk.tex
	pdflatex talk.tex

outline: outline.tex
	pdflatex outline.tex

clean:
	rm -f *.aux
	rm -f *.toc
	rm -f *.bbl
	rm -f *.blg
	rm -f *.out
	rm -f *.bcf
	rm -f *.log
	rm -f *.run.xml
	rm -f *.pyg
	rm -f *.snm
	rm -f *.nav


