experiment:
  minRaysPerSample: 1000
  maxRaysPerSample: 1000000
  mseThreshold: 0.01087 # this is the volume weighting adjusted threshold (scaled the original 0.005 by thickness * mesh.surface )
  adaptiveSteps: 8
  useReflections: true

compute:
  repetitions: 1
  backend: Cuda_NvidiaGpu_GpuCuda
  parallelMode: single
  numDevices: 4
  nPerNode: 1
