#!/usr/bin/env python3

"""Generate the child pipelines used by the root GitLab pipeline."""

from __future__ import annotations

import argparse
from pathlib import Path


COMPILE_ONLY_PIPELINE = """\
# Generated by script/ci/generate-gitlab.py. Do not edit.
stages:
  - run-tests

pre-commit:
  stage: run-tests
  image: ubuntu:24.04
  script:
    - bash script/ci/pre-commit.sh
  interruptible: true
  tags:
    - x86_64
    - cpuonly

gcc-13-compile-only:
  stage: run-tests
  image: ubuntu:24.04
  variables:
    HASE_CI_BUILD_DIR: build/gitlab-compile-only
    HASE_CI_COMPILER: gcc
    HASE_CI_COMPILER_VERSION: "13"
    HASE_CI_CUDA: "no"
    HASE_CI_HIP: "no"
    HASE_CI_MPI: "off"
    HASE_CI_HWLOC: "yes"
    HASE_CI_RUN_PYTHON_INSTALL: "0"
    HASE_CI_RUN_DIAGNOSTICS: "0"
    HASE_CI_RUN_INSTALLED_SMOKE: "0"
    HASE_CI_RUN_MPI_CONFIGURE: "0"
    HASE_CI_RUN_EXAMPLE: "0"
    HASE_CI_RUN_CTEST: "0"
    HASE_CI_RUN_PYTEST: "0"
    OPENPMD_RUNTIME_BACKEND: adios
  script:
    - bash script/ci/run.sh
  interruptible: true
  tags:
    - x86_64
    - cpuonly
"""

RUNTIME_CPU_PIPELINE = """\
# Generated by script/ci/generate-gitlab.py. Do not edit.
stages:
  - run-tests

gcc-13-runtime-cpu:
  stage: run-tests
  image: ubuntu:24.04
  variables:
    HASE_CI_BUILD_DIR: build/gitlab-runtime-cpu
    HASE_CI_COMPILER: gcc
    HASE_CI_COMPILER_VERSION: "13"
    HASE_CI_CUDA: "no"
    HASE_CI_HIP: "no"
    HASE_CI_MPI: "off"
    HASE_CI_HWLOC: "yes"
    OPENPMD_RUNTIME_BACKEND: adios
  script:
    - bash script/ci/run.sh
  interruptible: true
  tags:
    - x86_64
    - cpuonly
"""

SPECIAL_PIPELINE = """\
# Generated by script/ci/generate-gitlab.py. Do not edit.
stages:
  - run-tests

julia-regressions:
  stage: run-tests
  image: ubuntu:24.04
  variables:
    HASE_CI_BUILD_DIR: build/gitlab-julia
    HASE_CI_COMPILER: gcc
    HASE_CI_COMPILER_VERSION: "13"
    HASE_CI_CUDA: "no"
    HASE_CI_HIP: "no"
    HASE_CI_MPI: "off"
    HASE_CI_HWLOC: "yes"
    HASE_CI_PYTEST_PATHS: gitlab/juliaASE/tests
    HASE_CI_RUN_CTEST: "0"
    HASE_CI_RUN_EXAMPLE: "0"
    OPENPMD_RUNTIME_BACKEND: adios
  script:
    - bash script/ci/run.sh
  interruptible: true
  tags:
    - x86_64
    - cpuonly
"""

PIPELINES = {
    "compile_only.yml": COMPILE_ONLY_PIPELINE,
    "runtime_cpu.yml": RUNTIME_CPU_PIPELINE,
    "special.yml": SPECIAL_PIPELINE,
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path.cwd(),
        help="directory for the generated child pipeline files",
    )
    return parser.parse_args()


def main() -> None:
    output_dir = parse_args().output_dir
    output_dir.mkdir(parents=True, exist_ok=True)
    for file_name, contents in PIPELINES.items():
        (output_dir / file_name).write_text(contents, encoding="utf-8")


if __name__ == "__main__":
    main()
