include_guard(GLOBAL)

function(hase_extract_cmake_definition_names argument_string out_var)
    string(
        REGEX MATCHALL
        "-D[^:= \t\r\n]+(:[^= \t\r\n]+)?="
        HASE_CMAKE_DEFINITIONS
        "${argument_string}"
    )
    set(HASE_CMAKE_DEFINITION_NAMES "")
    foreach(HASE_CMAKE_DEFINITION IN LISTS HASE_CMAKE_DEFINITIONS)
        string(
            REGEX REPLACE
            "^-D([^:=]+)(:[^=]+)?=$"
            "\\1"
            HASE_CMAKE_DEFINITION_NAME
            "${HASE_CMAKE_DEFINITION}"
        )
        list(APPEND HASE_CMAKE_DEFINITION_NAMES "${HASE_CMAKE_DEFINITION_NAME}")
    endforeach()
    list(REMOVE_DUPLICATES HASE_CMAKE_DEFINITION_NAMES)
    set(${out_var} "${HASE_CMAKE_DEFINITION_NAMES}" PARENT_SCOPE)
endfunction()

# Target-platform and ABI settings that must agree across the thin frontend,
# its resident runtime, and the HASE-managed openPMD provider stages. Search
# paths are intentionally absent: scikit-build adds temporary Python prefixes
# that must not be cached by the resident runtime.
set(HASE_FORWARDED_TARGET_TOOLCHAIN_VARIABLES
    CMAKE_TOOLCHAIN_FILE
    CMAKE_GENERATOR_INSTANCE
    CMAKE_SYSTEM_NAME
    CMAKE_SYSTEM_VERSION
    CMAKE_SYSTEM_PROCESSOR
    CMAKE_SYSROOT
    CMAKE_SYSROOT_COMPILE
    CMAKE_SYSROOT_LINK
    CMAKE_STAGING_PREFIX
    CMAKE_FIND_ROOT_PATH
    CMAKE_FIND_ROOT_PATH_MODE_PROGRAM
    CMAKE_FIND_ROOT_PATH_MODE_LIBRARY
    CMAKE_FIND_ROOT_PATH_MODE_INCLUDE
    CMAKE_FIND_ROOT_PATH_MODE_PACKAGE
    CMAKE_OSX_ARCHITECTURES
    CMAKE_OSX_DEPLOYMENT_TARGET
    CMAKE_OSX_SYSROOT
    CMAKE_MSVC_RUNTIME_LIBRARY
    CMAKE_CUDA_RUNTIME_LIBRARY
    CMAKE_C_COMPILER
    CMAKE_CXX_COMPILER
    CMAKE_CUDA_COMPILER
    CMAKE_HIP_COMPILER
    CMAKE_C_COMPILER_LAUNCHER
    CMAKE_CXX_COMPILER_LAUNCHER
    CMAKE_CUDA_COMPILER_LAUNCHER
    CMAKE_HIP_COMPILER_LAUNCHER
    CMAKE_C_COMPILER_TARGET
    CMAKE_CXX_COMPILER_TARGET
    CMAKE_CUDA_COMPILER_TARGET
    CMAKE_HIP_COMPILER_TARGET
    CMAKE_C_COMPILER_EXTERNAL_TOOLCHAIN
    CMAKE_CXX_COMPILER_EXTERNAL_TOOLCHAIN
    CMAKE_CUDA_COMPILER_EXTERNAL_TOOLCHAIN
    CMAKE_HIP_COMPILER_EXTERNAL_TOOLCHAIN
    CMAKE_C_FLAGS
    CMAKE_CXX_FLAGS
    CMAKE_CUDA_FLAGS
    CMAKE_HIP_FLAGS
    CMAKE_C_FLAGS_DEBUG
    CMAKE_CXX_FLAGS_DEBUG
    CMAKE_CUDA_FLAGS_DEBUG
    CMAKE_HIP_FLAGS_DEBUG
    CMAKE_C_FLAGS_RELEASE
    CMAKE_CXX_FLAGS_RELEASE
    CMAKE_CUDA_FLAGS_RELEASE
    CMAKE_HIP_FLAGS_RELEASE
    CMAKE_C_FLAGS_RELWITHDEBINFO
    CMAKE_CXX_FLAGS_RELWITHDEBINFO
    CMAKE_CUDA_FLAGS_RELWITHDEBINFO
    CMAKE_HIP_FLAGS_RELWITHDEBINFO
    CMAKE_C_FLAGS_MINSIZEREL
    CMAKE_CXX_FLAGS_MINSIZEREL
    CMAKE_CUDA_FLAGS_MINSIZEREL
    CMAKE_HIP_FLAGS_MINSIZEREL
    CMAKE_EXE_LINKER_FLAGS
    CMAKE_SHARED_LINKER_FLAGS
    CMAKE_MODULE_LINKER_FLAGS
    CMAKE_EXE_LINKER_FLAGS_DEBUG
    CMAKE_SHARED_LINKER_FLAGS_DEBUG
    CMAKE_MODULE_LINKER_FLAGS_DEBUG
    CMAKE_EXE_LINKER_FLAGS_RELEASE
    CMAKE_SHARED_LINKER_FLAGS_RELEASE
    CMAKE_MODULE_LINKER_FLAGS_RELEASE
    CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO
    CMAKE_SHARED_LINKER_FLAGS_RELWITHDEBINFO
    CMAKE_MODULE_LINKER_FLAGS_RELWITHDEBINFO
    CMAKE_EXE_LINKER_FLAGS_MINSIZEREL
    CMAKE_SHARED_LINKER_FLAGS_MINSIZEREL
    CMAKE_MODULE_LINKER_FLAGS_MINSIZEREL
    CMAKE_INTERPROCEDURAL_OPTIMIZATION
    CMAKE_INTERPROCEDURAL_OPTIMIZATION_DEBUG
    CMAKE_INTERPROCEDURAL_OPTIMIZATION_RELEASE
    CMAKE_INTERPROCEDURAL_OPTIMIZATION_RELWITHDEBINFO
    CMAKE_INTERPROCEDURAL_OPTIMIZATION_MINSIZEREL
)

function(hase_collect_initial_target_toolchain_variables out_var)
    get_cmake_property(HASE_PRE_PROJECT_CACHE_VARIABLES CACHE_VARIABLES)
    set(HASE_INITIAL_TARGET_TOOLCHAIN_VARIABLES "")
    foreach(
        HASE_PRE_PROJECT_CACHE_VARIABLE
        IN
        LISTS HASE_PRE_PROJECT_CACHE_VARIABLES
    )
        if(
            HASE_PRE_PROJECT_CACHE_VARIABLE
                IN_LIST
                HASE_FORWARDED_TARGET_TOOLCHAIN_VARIABLES
        )
            list(
                APPEND
                HASE_INITIAL_TARGET_TOOLCHAIN_VARIABLES
                "${HASE_PRE_PROJECT_CACHE_VARIABLE}"
            )
        endif()
    endforeach()
    set(${out_var} "${HASE_INITIAL_TARGET_TOOLCHAIN_VARIABLES}" PARENT_SCOPE)
endfunction()
