set(HASE_OPENPMD_PROBE_DEFINES "")
if(HASE_OPENPMD_ACTUAL_PROVIDER STREQUAL "bundled")
    if(HASE_OPENPMD_USE_ADIOS2)
        list(APPEND HASE_OPENPMD_PROBE_DEFINES HASE_OPENPMD_PROBE_ADIOS)
        if(HASE_OPENPMD_USE_SST)
            list(APPEND HASE_OPENPMD_PROBE_DEFINES HASE_OPENPMD_PROBE_ADIOS_SST)
        endif()
    endif()
    if(HASE_OPENPMD_USE_HDF5)
        list(APPEND HASE_OPENPMD_PROBE_DEFINES HASE_OPENPMD_PROBE_HDF5)
    endif()
else()
    if(DEFINED openPMD_HAVE_ADIOS2 AND openPMD_HAVE_ADIOS2)
        if(DEFINED ADIOS2_HAVE_SST AND ADIOS2_HAVE_SST)
            list(APPEND HASE_OPENPMD_PROBE_DEFINES HASE_OPENPMD_PROBE_ADIOS_SST)
        endif()
        list(APPEND HASE_OPENPMD_PROBE_DEFINES HASE_OPENPMD_PROBE_ADIOS)
    endif()
    if(DEFINED openPMD_HAVE_HDF5 AND openPMD_HAVE_HDF5)
        list(APPEND HASE_OPENPMD_PROBE_DEFINES HASE_OPENPMD_PROBE_HDF5)
    endif()
endif()

add_executable(
    HaseOpenPmdBackendProbe
    "${CMAKE_CURRENT_SOURCE_DIR}/src/openpmd/backendProbe.cpp"
)
set_target_properties(
    HaseOpenPmdBackendProbe
    PROPERTIES
        BUILD_RPATH_USE_ORIGIN ON
        BUILD_RPATH "${HASE_BUILD_TREE_RPATH}"
        INSTALL_RPATH "${HASE_INSTALL_RPATH}"
        INSTALL_RPATH_USE_LINK_PATH ON
)
target_include_directories(
    HaseOpenPmdBackendProbe
    PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}/include"
)
target_compile_definitions(
    HaseOpenPmdBackendProbe
    PRIVATE ${HASE_OPENPMD_PROBE_DEFINES} HASE_OPENPMD_BACKEND_PROBE_STANDALONE
)
target_link_libraries(HaseOpenPmdBackendProbe PRIVATE openPMD::openPMD)
